#!/bin/bash

# see if the miner is running
PID_FILE=${HOME}/Desktop/miner.pid
# For AMD, gpus are labeled cl0, cl1, cl2....
# For NVidia, gpus are labeled cu0, cu1, cu2.....
function detectGPUs() {
  test=`lspci|grep VGA|grep "Advanced Micro Devices"`
  if [ $? -eq 0 ]
  then
     # it's AMD
     GPU_LABEL="cl0"
  else
     # it's Nvidia
     GPU_LABEL="cu0"
  fi
}

# check that the pid file exists
if [ -r ${PID_FILE} ]
then
  # pid exists, see if the process is running
  PID=`cat ${PID_FILE}`
  # check that the process is an actual ethminer process
  ps -q ${PID}|grep -sq ethminer
  IS_ETHMINER="$?"
  if [ "${IS_ETHMINER}" -eq "0" ]
  then
    echo "=============================================================="
    echo "| ethminer appears to be running                             |"
    if [ "$1" == "-f" ]
    then
      echo "| tailing miner log file. To stop tailing logs, press CTRL+C |"
      echo "=============================================================="
      tail -20f ${HOME}/Desktop/miner.log
    else
      detectGPUs
      echo "| showing most recent hash rates:                            |"
      echo "=============================================================="
      tail -10 ${HOME}/Desktop/miner.log|grep ${GPU_LABEL}
      echo ""
      echo "To see mining wallet status, visit https://ethermine.org/miners/94F533789cf2b9b33c3bEf1d3200c8f9B2792558/dashboard"
      echo "to see web stats on gpus, visit http://allset:8080"
    fi
  else
    echo "ethminer does not appear to be running. To start mining, execute \"start_miner\""
  fi
else
  echo "No PID file exists. To run ethminer, execute \"start_miner\""
fi
