#!/bin/bash

# stratum1+tcp://0x94F533789cf2b9b33c3bEf1d3200c8f9B2792558@us1.ethermine.org:4444
# Dashboard:
#     https://ethermine.org/miners/94F533789cf2b9b33c3bEf1d3200c8f9B2792558/dashboard
# teamredminer -o stratum+tcp://us2.ethermine.org:4444 -a ethash -u 0x94F533789cf2b9b33c3bEf1d3200c8f9B2792558

MINING_PROTOCOL="stratum+tcp"
MINING_ALGO="ethash"
MINING_WALLET="0x"$(< ${HOME}/ethminer/walletid)
MINING_HOST="us2.ethermine.org"
MINING_PORT="4444"
API_PORT=8080

function wait_for_gpus() {
  # get clinfo and wait for cards to be ready
  gpu_count=$(clinfo -l|grep Device|wc -l)
  if [ ${gpu_count} -gt 0 ]
  then
    date | tee -a /home/allset/ethminer/miner.log
    echo "We have at least 1 gpu" | tee -a /home/allset/ethminer/miner.log
    return
  else
    date | tee -a /home/allset/ethminer/miner.log
    echo "clinfo detected no gpus" | tee -a /home/allset/ethminer/miner.log
    clinfo | tee -a /home/allset/ethminer/miner.log
    # no gpus ready
    sleep 10
  fi
  # try again
  gpu_count=$(clinfo -l|grep Device|wc -l)
  if [ ${gpu_count} -gt 0 ]
  then
    date | tee -a /home/allset/ethminer/miner.log
    echo "We have at least 1 gpu" | tee -a /home/allset/ethminer/miner.log
    return
  else
    date | tee -a /home/allset/ethminer/miner.log
    echo "clinfo detected no gpus" | tee -a /home/allset/ethminer/miner.log
    clinfo | tee -a /home/allset/ethminer/miner.log
    # no gpus ready, done
    exit -1
  fi
}

function stop_display() {
  # make sure GPUs exist
  gpu_count=$(clinfo -l|grep Device|wc -l)
  if [ ${gpu_count} -gt 0 ]
  then
    date | tee -a /home/allset/ethminer/miner.log
    echo "Found ${gpu_count} GPU(s), stopping display" | tee -a /home/allset/ethminer/miner.log
    sudo systemctl stop lxdm
  else
    date | tee -a /home/allset/ethminer/miner.log
    echo "Found ${gpu_count} GPU(s), exiting script" | tee -a /home/allset/ethminer/miner.log
    exit -2
  fi
}

wait_for_gpus
stop_display

# build pool
MINING_POOL="${MINING_PROTOCOL}://${MINING_HOST}:${MINING_PORT}"
#build command
# teamredminer -o stratum+tcp://us2.ethermine.org:4444 -a ethash -u 0x94F533789cf2b9b33c3bEf1d3200c8f9B2792558
MINING_CMD="teamredminer -o ${MINING_POOL} -a ${MINING_ALGO} -u ${MINING_WALLET}"
echo "Running Mining Command: ${MINING_CMD}"
echo ""
echo "To see miner status, run \"miner_status\""
echo "To stop mining, run \"stop_miner\""
echo "To see stats in a web browser, visit http://allset:8080"
echo "To see mining dashboard, visit https://ethermine.org/miners/${MINING_WALLET}/dashboard"
echo "========================================="
exec ${MINING_CMD} >> ${HOME}/ethminer/miner.log 2>&1 &
echo "$!" > ${HOME}/ethminer/miner.pid
