name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select the Cassandra or DSE version to run tests against'
        required: true
        default: '4.0'
        type: choice
        options:
          - '3.11'
          - '4.0'
          - '6.8'
          - 'ALL'
      flag:
        description: 'Toggle this boolean to set flag variable'
        required: false
        type: boolean
        default: false
        

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Cassandra or DSE version: $VERSION"
          echo "Flag set: $FLAG"
        env:
          VERSION: ${{ inputs.version }}
          FLAG: ${{ inputs.flag }}
  skip-job:
    if: ${{ inputs.version == '3.11' || inputs.version == 'ALL' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This job should run if the input is 3.11 or ALL. Should be skipped otherwise."
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - "3.11.14"
        - "4.0.7"
        - "6.8.29"
    env:
      INPUT_VER: ${{ inputs.version }}
      MATRIX_VER: ${{ matrix.version }}
    steps:
      - name: conditional
        if: ${{ inputs.version == 'ALL' || startsWith( matrix.version, inputs.version ) }}
        run: |
          echo "Run with input version: $INPUT_VER and matrix version: $MATRIX_VER"