name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select the Cassandra or DSE version to run tests against'
        required: true
        default: '4.0'
        type: choice
        options:
          - '3.11'
          - '4.0'
          - '6.8'
          - 'ALL'
      flag:
        description: 'Toggle this boolean to set flag variable'
        required: false
        type: boolean
        default: false
        

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Cassandra or DSE version: $VERSION"
          echo "Flag set: $FLAG"
        env:
          VERSION: ${{ inputs.version }}
          FLAG: ${{ inputs.flag }}
  skip-job:
    if: ${{ inputs.version == '3.11' || inputs.version == 'ALL' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This job should run if the input is 3.11 or ALL. Should be skipped otherwise."
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - "3.11.14"
        - "4.0.7"
        - "6.8.29"
        workflowVersion:
        - ${{ inputs.version }}
        integration_test:
        # Single worker tests:
        - additional_serviceoptions
        - additional_volumes
        # - delete_node_terminated_container # This does not test any operator behavior
        - podspec_simple
        # - smoke_test_oss # Converted to test_all_the_things, see below job
        # - smoke_test_dse # Converted to test_all_the_things, see below job
        - terminate
        - timeout_prestop_termination
        # - upgrade_operator # See kind_311_tests job
        - webhook_validation
        # Three worker tests:
        # - canary_upgrade # See kind_311_tests job
        - config_change_condition
        # - cdc_successful # CDC is OSS only , see kind_311_tests and kind_40_tests jobs
        # - delete_node_lost_readiness # DSE specific behavior see kind_dse_tests job
        - host_network
        - internode-encryption-generated
        #- no_infinite_reconcile # smoke_test_* should take care of this
        - node_replace
        - nodeport_service
        #- rolling_restart #TODO: Fails against DSE, fix in https://github.com/k8ssandra/cass-operator/issues/459
        - stop_resume
        - superuser-secret-generated
        - superuser-secret-provided
        - test_bad_config_and_fix
        - test_mtls_mgmt_api
        # More than 3 workers tests:
        - add_racks
        #- additional_seeds #TODO: Fails against C* 4.0, fix in https://github.com/k8ssandra/cass-operator/issues/459
        - cluster_wide_install
        - config_change
        #- config_secret #TODO: Fails against DSE, fix in https://github.com/k8ssandra/cass-operator/issues/459
        - multi_cluster_management
        #- oss_test_all_the_things # This is now the smoke test, see kind_smoke_tests job
        - scale_down
        # - scale_down_not_enough_space # Not enough stable test
        #- scale_down_unbalanced_racks #TODO: Fails against C* 4.0 and DSE, fix in https://github.com/k8ssandra/cass-operator/issues/459
        - scale_up
        - scale_up_stop_resume
        - seed_selection
        # - config_fql # OSS only, see above job
        #- decommission_dc #TODO: Fails against DSE, fix in https://github.com/k8ssandra/cass-operator/issues/459
        # - stop_resume_scale_up # Odd insufficient CPU issues in kind+GHA
        exclude:
        - version: "3.11.14"
          workflowVersion: "4.0"
        - version: "3.11.14"
          workflowVersion: "6.8"
        - version: "4.0.7"
          workflowVersion: "3.11"
        - version: "4.0.7"
          workflowVersion: "6.8"
        - version: "6.8.29"
          workflowVersion: "3.11"
        - version: "6.8.29"
          workflowVersion: "4.0"
    env:
      CGO_ENABLED: 0
      M_INTEG_DIR: ${{ matrix.integration_test }}
      M_SERVER_VERSION: ${{ matrix.version }}
    steps:
      - name: conditional
        if: ${{ inputs.version == 'ALL' || startsWith( matrix.version, inputs.version ) }}
        run: |
          echo "Run with input version: $INPUT_VER and matrix version: $MATRIX_VER"
      - name: set environment for DSE tests
        if: ${{ startsWith( matrix.version, '6.8' ) }}
        run: |
          echo "M_SERVER_IMAGE=datastax/dse-mgmtapi-6_8:6.8.29-jdk8" >> $GITHUB_ENV
          echo "M_SERVER_TYPE=dse" >> $GITHUB_ENV
      - name: show ENV
        run: |
          env|sort